### ISSUE TITLE
Add to app list on openboardformat.org

### ISSUE THREAD

**Issue by klues** [CoughDrop/openboardformat#3]
We're developing "AsTeRICS Grid", see [sources on github](https://github.com/asterics/AsTeRICS-Grid) and live version on [grid.asterics.eu](https://grid.asterics.eu/#main).

In the latest release we added import of OBF (`.obf` and `.obz`) and I wanted to ask if you could add AsTeRICS Grid to the [partners page of openboardformat.org](https://www.openboardformat.org/partners)? Currently we are supporting only import, not export.

You can test the functionality by:
1. navigate to grid.asterics.eu [grid.asterics.eu](https://grid.asterics.eu/#main)
2. click "Use AsTeRICS Grid without registration"
3. Go to "Manage grids" in the menu on the left
4. Click "More" (upper right) -> "Clear an import from file" -> select `.obf` or `.obz` file

**Comment by whitmer** [comment]
Should be added! Thanks!
